# -*- coding: utf-8 -*-
"""Depth_First_Search.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JrsTSMvGA8VN1SEtKhqStb15U-D_jHnF

Depth First Search
"""

#Add set of nodes
Nodes = [1,2,3,4,5]

#Add set of arcs/edges
Edges = [[1,2],[1,3],[2,4],[2,5]]

#Introduce stack S
S = []
S.append(1)

#Introduce explored parameter
explored = {}
for i in Nodes:
  explored[i] = 0
explored[1] = 1

# Introduce parent parameter
parent = {}
for i in Nodes:
  parent[i] = -1

while S != []:
  v = S[0]
  S.remove(v)
  for w in Nodes:
    if [v,w] in Edges and explored[w] == 0:
      S.append(w)
      explored[w] = 1
      parent[w] = v

print(parent)

